# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/addUser
Content-Type: application/json

{
  "account" : "eunjin1111",
  "password": "1234",
  "name": "eunjin",
  "mobile" : "010-1234-5678",
  "zipcode" : "41235",
  "address" : "대구광역시 달성군",
  "email" : "eunjin10@12312"
}

###

POST http://localhost:8080/addBasket
Content-Type: application/json

{
  "product" : "티셔츠",
  "price": "10000",
  "count": "5",
  "total" : "50000"
}

###

GET http://localhost:8080/basket
Accept: application/json

###

DELETE http://localhost:8080/deleteBasket/1
Accept: application/json

###

PUT http://localhost:8080/updateBasket/1
Content-Type: application/json

{
  "product" : "티셔츠",
  "price": "10000",
  "count": "6",
  "total" : "60000"
}

###